[tool.black]
line-length = 88
target-version = ['py310']
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
known_first_party = ["app"]
src_paths = ["app"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
disallow_untyped_calls = false
warn_unused_ignores = true
warn_return_any = false
warn_unused_configs = true
no_implicit_optional = false
show_error_codes = true
pretty = true
check_untyped_defs = true
exclude = "^(tests|alembic)(/|\\\\)"

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false

[[tool.mypy.overrides]]
module = ["alembic.*"]
ignore_errors = true